server:
  port: 8080

spring:
  application:
    name: fflix-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:fflix
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none
              create-source: metadata
              create-target: src/main/resources/db/changelog/changes/db.quickstart.sql
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    url: jdbc:h2:mem:fflix
    user: sa
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest

okta:
  oauth2:
    issuer: https://dev-q882ymdxpejid746.us.auth0.com/
    audience: https://w2n-challenge-api.com