create table spaceship (
    id integer generated by default as identity,
    title_id integer not null,
    max_speed varchar(50),
    affiliation varchar(100),
    captain varchar(100),
    model varchar(100),
    name varchar(100) not null,
    weapons varchar(255),
    crew_size integer,
    status enum ('ACTIVE','DESTROYED','LOST','UNKNOWN') not null,
    primary key (id)
 );

create table title (
    id integer generated by default as identity,
    release integer,
    name varchar(100) not null,
    type enum ('MOVIE','SERIES') not null,
    primary key (id)
);

alter table if exists spaceship add constraint title_fk foreign key (title_id) references title;